import { useEffect, useState, useRef } from 'react';
import { BookOpen, Loader2 } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import './ReviewView.css';

const API_BASE = import.meta.env.VITE_API_BASE || 'http://localhost:8000';

export default function ReviewView({ job }) {
  const { id: jobId } = job;
  const [review, setReview] = useState('');
  const [loading, setLoading] = useState(true);
  const [streaming, setStreaming] = useState(false);
  const [error, setError] = useState(null);
  const abortRef = useRef(null);
  useEffect(() => {
    let isActive = true;
    const controller = new AbortController();
    abortRef.current = controller;

    const fetchReview = async () => {
      setLoading(true);
      setStreaming(true);
      setError(null);
      setReview('');
      
      try {
        const res = await fetch(`${API_BASE}/api/jobs/${jobId}/review`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ question: '' }), 
          signal: controller.signal,
        });

        if (!res.ok) {
          throw new Error('Failed to start review generation.');
        }

        const reader = res.body.getReader();
        const decoder = new TextDecoder();
        let accumulated = '';
        let buffer = '';

        while (true) {
          const { done, value } = await reader.read();
          if (done) break;

          buffer += decoder.decode(value, { stream: true });
          const lines = buffer.split('\n');
          // The last element is either an incomplete line or an empty string (if buffer ended with \n)
          // Keep it in the buffer for the next chunk
          buffer = lines.pop();

          for (const line of lines) {
            if (line.startsWith('data: ')) {
              const payload = line.slice(6).trim();
              if (payload === '[DONE]') continue;
              try {
                const parsed = JSON.parse(payload);
                if (parsed.token) {
                  accumulated += parsed.token;
                  if (isActive) setReview(accumulated);
                }
              } catch {
                // skip malformed SSE data
              }
            }
          }
        }
      } catch (err) {
        if (err.name !== 'AbortError' && isActive) {
          setError(err.message || 'An error occurred while generating the review.');
        }
      } finally {
        if (isActive) {
          setLoading(false);
          setStreaming(false);
        }
      }
    };

    fetchReview();

    return () => {
      isActive = false;
      controller.abort();
    };
  }, [jobId]);

  return (
    <div className="review-layout">
      <div className="review-container">
        <div className="review-header">
          <div className="review-icon">
            <BookOpen size={24} />
          </div>
          <div>
            <h2 className="review-title">Project Architecture Review</h2>
            <div className="review-subtitle">
              Generated by AI to help new developers understand the codebase structure.
            </div>
          </div>
        </div>

        {loading && !review ? (
          <div className="review-loading">
            <Loader2 size={48} className="review-spinner" />
            <div>Generating comprehensive project review...</div>
          </div>
        ) : error ? (
          <div className="review-content" style={{ color: 'var(--danger)' }}>
            ⚠️ {error}
          </div>
        ) : (
          <div className="review-content">
            <ReactMarkdown>{review}</ReactMarkdown>
            {streaming && <span className="review-streaming">Generating...</span>}
          </div>
        )}
      </div>
    </div>
  );
}
